#!/bin/bash

#Author: Jafeth

#Date created: 04/Jun/2021

#Description
#Creates a backup in ~/Documents folder of all files in the home directory

echo "Hi ${USER}"
echo "I will now backup your home directory, $HOME"
currentdir=$(pwd)
echo "You are running this script from $currentdir"
echo "Therefore, I will save the backup in $currentdir"

#tar -cvf ~/Documents/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".zip ~/* 2>/dev/null
tar -cf $currentdir/my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar $HOME/* 2>/dev/null

echo "Backup completed successfully"
exit 0
